### ISSUE TITLE
小京鱼app显示传入参数非法

### ISSUE THREAD

**Issue by dalydxc** [espressif/esp-joylink#11]
设备接入京东成功后，在小京鱼app上删除设备
1、如果这时将设备重启，再添加设备，会显示传入参数非法，然后小京鱼app不能绑定设备
2、如果不重启设备，则能添加设备

**Comment by xuhongv** [comment]
你的是京东哪个版本的？8266吗

**Comment by dalydxc** [comment]
最新的那个版本，我现在只能是提供一个按键用来清除整个NVS分区，清除注册信息，防止用户误操作在小京鱼app上删除设备后，不能再次注册

**Comment by dalydxc** [comment]
> 你的是京东哪个版本的？8266吗

最新的那个版本，我现在只能是提供一个按键用来清除整个NVS分区，清除注册信息，防止用户误操作在小京鱼app上删除设备后，不能再次注册

**Comment by dalydxc** [comment]
> 你的是京东哪个版本的？8266吗

说错了，是 joylink sdk version 2.0.12版本，我怀疑NVS中已经有注册信息了，所以会出现这个错误

**Comment by xiewenxiang** [comment]
@dalydxc 
如果在APP中删除设备，模组这里需要手动清除注册信息，因为APP那里删除设备不会告知模组这里

**Comment by dalydxc** [comment]
> @dalydxc
> 如果在APP中删除设备，模组这里需要手动清除注册信息，因为APP那里删除设备不会告知模组这里

好的，谢谢，所以我这边提供了一个按键用于恢复出厂设置，防止用户误操作后不能不能重新注册

**Comment by xuhongv** [comment]
京东那边好像说是 清除feedid功能，一大堆功能。

**Comment by xuhongv** [comment]
其实你设备达到配网模式前就可以清除所有设备信息了。没必然加个按键、 。

**Comment by xiewenxiang** [comment]
如果在APP上删除了设备，模组这里需要自己删除绑定的信息，调用 restore 接口就行了
