### ISSUE TITLE
能否使用flash_download_tools烧录？

### ISSUE THREAD

**Issue by hizhsj** [espressif/esp-joylink#14]
现在采用的是make flash指令烧录，想做成跟之前的产品兼容也方便生产，请问如果使用flash_download_tools工具该如何设置参数？

**Comment by xiewenxiang** [comment]
一样的，和烧录其他 example 的bin一样，指定文件路径和烧录地址即可

**Comment by hizhsj** [comment]
使用ESPFlashDownloadTool_v3.6.4时，烧录地址与对应的文件是：
0x00000 - boot_v1.7.bin
0x01000 - user1.2048.new.5.bin
0x1f8000 - blank_12k.bin
0x1fb000 - blank.bin
0x1fc000 - esp_init_data_default.bin
0x1fe000 - blank.bin
这是采用之前的编译方式，即在虚拟机下运行lubuntu系统，编译生成的user1.2048.new.5.bin，烧录之后是可以正常运行的，现在是运行mingw32.exe，编译完成之后，make flash烧录之后，也能够正常运行。现在用example/light_demo/build/下的esp_joylink.bin替换user1.2048.new.5.bin，烧录完成之后，esp8266不停的重启，无法正常运行。

**Comment by hizhsj** [comment]
@xiewenxiang

**Comment by xiewenxiang** [comment]
@hizhsj 
新的joylink 已经用3.0以上版本的SDK，生成的bin以及partition分区表都不一样了，需要擦除芯片，完整的烧录新生成的所有bin

**Comment by hizhsj** [comment]
@xiewenxiang 
考虑到生产的时候，在只提供若干bin文件而不是原工程代码，这种情况下，如何实现烧录呢？make flash指令似乎只有在原工程目录下才正常执行。如果能使用ESPFlashDownloadTool_v3.6.4工具烧录，麻烦详细说一下需要烧录的Bin文件和对应的地址。

**Comment by hizhsj** [comment]
如果有其他的解决方案也可以提供一下，谢谢。

**Comment by xiewenxiang** [comment]
一般joylink demo生成的bin文件应该有这几个：

```c
0x0000      bootloader.bin 
0xd000      ota_data_initial.bin
0x10000     esp-joylink.bin
0x8000      joylink_demo.bin     
```

其中 joylink_demo.bin 是 partition 分区表，在dmeo中是没有的，用户自己定义一个分区表，用来OTA以及放一机一密的key

然后将所有的bin打包成一个bin，从0地址烧录

生产的话，一般应该每个芯片烧录两次的，因为每个芯片都有一个独一无二的key要烧录

**Comment by hizhsj** [comment]
@xiewenxiang 
谢谢指导，按照上面的烧录方式，是可以正常烧录的，只不过0x8000烧录的是joylink_8266_partitions.bin,这个是导入joylink_8266_partitions.csv生成的吧？
另外，请教一下，如何把所有的bin打包成一个Bin呢？

**Comment by xiewenxiang** [comment]
@hizhsj 
是的。
将所有bin打包成一个，网上也有很多工具，就是二进制合并软件

**Comment by hizhsj** [comment]
@xiewenxiang 
好的，谢谢了。

**Comment by xiewenxiang** [comment]
@hizhsj 
好的 如果还有问题，可以重新打开这个issue 或者另提一个 issue。
