### ISSUE TITLE
joylink更新了

### ISSUE THREAD

**Issue by hizhsj** [espressif/esp-joylink#15]
现在京东官方的joylink固件已经更新到2.0.19，而且配网方式也从默认的一键配置更改成了softap，请问esp-joylink什么时候也更新呢？

**Comment by xuhongv** [comment]
本来就支持 softap配网，只是现在新版不允许一键配置罢了。京东微联对接一堆坑；

**Comment by xiewenxiang** [comment]
softap 自主激活  代理激活  smartconfig ，thunder 我们都已是配好，近期会放出去

**Comment by xuhongv** [comment]
亲，我上几个月提交的 issues 您都没看过，一直任务异常，这个 task 我都不知道哪里定义的！
@xiewenxiang

**Comment by xiewenxiang** [comment]
@xuhongv 稍等 我一会看一下

**Comment by xuhongv** [comment]
- 麻烦看看ISSUES @xiewenxiang

**Comment by xuhongv** [comment]
@xiewenxiang 请问什么时候放出来一版，这边有新客户要接入 joylink 了。

**Comment by xiewenxiang** [comment]
请拉最新 master 分支
