### ISSUE TITLE
自动化测试——安全检测

### ISSUE THREAD

**Issue by dalydxc** [espressif/esp-joylink#16]
京东自动化测试中的“双向认证 - 异常情况测试”一直显示不通过，该如何操作？

**Comment by dalydxc** [comment]
“我们同事说可能是你们固件的问题。比方说第一项给你下发了一个错误的随机数按理说你们应该是识别出来哈，但是还是正常写入了”，这是京东给我的回复，我用demo测，“双向认证 - 异常情况测试”也是无法通过

**Comment by xiewenxiang** [comment]
@dalydxc 用的是哪一个commit  我来测试下

**Comment by dalydxc** [comment]
> @dalydxc用的是哪一个commit我来测试下

Commits on Jul 29, 2019    Joylink SDK 2.0.15

**Comment by dalydxc** [comment]
> @dalydxc 用的是哪一个commit 我来测试下

已解决，没开JOYLINK_DEVICE_AUTH这个宏定义

**Comment by xiewenxiang** [comment]
好的
