### ISSUE TITLE
ota failed

### ISSUE THREAD

**Issue by hizhsj** [espressif/esp-joylink#17]
调试OTA功能的时候，重启了，查看日志发现：boot parition NULL,.在烧录的时候，有一个：partitions_singleapp.bin，烧录位置是0x8000.都是默认的配置，为什么会报错呢？esp_joylink.bin的烧录地址是0x10000，那么FLASH里面的布局是怎么样的？跟之前的版本有user1.bin 和user2.bin的概念不一样吗？

**Comment by xuhongv** [comment]
- 请问你的编译环境是？我windows编译报错了；

`section `.dram0.bss' will not fit in region `dram0_0_seg`

**Comment by xiewenxiang** [comment]
[joylink_8266_partitions.csv.zip](https://github.com/espressif/esp-joylink/files/3868158/joylink_8266_partitions.csv.zip)


@hizhsj  用这个 partition table

**Comment by xiewenxiang** [comment]
@xuhongv 
是8266 编译报错了还是32？

**Comment by xuhongv** [comment]
esp32 @xuhongv

**Comment by xuhongv** [comment]
貌似内存不够

```
AR build/xtensa-debug-module/libxtensa-debug-module.a
LD build/esp-joylink.elf
e:/espressif/esp32/msys32_20190611/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/Esp32/esp-idf/home/XuHongYss/esp-joylink/examples/light_demo/build/esp-joylink.elf section `.dram0.bss' will not fit in region `dram0_0_seg'
e:/espressif/esp32/msys32_20190611/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: region `dram0_0_seg' overflowed by 8752 bytes
collect2.exe: error: ld returned 1 exit status
make: *** [E:/Espressif/Esp32/msys32_20190611/home/XuHongYss/esp-idf/make/project.mk:432：/e/Espressif/Esp32/esp-idf/home/XuHongYss/esp-joylink/examples/light_demo/build/esp-joylink.elf] 错误 1

```

**Comment by xiewenxiang** [comment]
@xuhongv  32用的是哪个版本的idf

**Comment by xuhongv** [comment]
3.0的话 编译不了，确实http组件；
我现在用3.1分支

**Comment by xuhongv** [comment]
master最新分支不支持 gun 编译，很纳闷，请问你是用 cmake 编译的吗 @xiewenxiang

**Comment by xuhongv** [comment]
因为上个月我是用 3.1分支编译的，可以成功，只是提示 那个wifi任务栈大小问题导致重启；

**Comment by xuhongv** [comment]
我现在的 esp32分区表足够多的：

```
nvs,      data, nvs,     0x9000,  0x4000
otadata,  data, ota,     0xd000,  0x2000
phy_init, data, phy,     0xf000,  0x1000
factory,  0,    0,       0x10000,   1200K
ota_0,    0,    ota_0,   ,          1200K
ota_1,    0,    ota_1,   ,          1200K
```

**Comment by xiewenxiang** [comment]
现在matsetr分支调试的时候是基于3.3，上面log报错的地方是 IRAM 超了
我没用使用cmake。

`esp-idf/components/esp32/ld/esp32.ld`

```c
MEMORY
{
  /* All these values assume the flash cache is on, and have the blocks this uses subtracted from the length
  of the various regions. The 'data access port' dram/drom regions map to the same iram/irom regions but
  are connected to the data port of the CPU and eg allow bytewise access. */

  /* IRAM for PRO cpu. Not sure if happy with this, this is MMU area... */
  iram0_0_seg (RX) :                 org = 0x40080000, len = 0x20000

  /* Even though the segment name is iram, it is actually mapped to flash
  */
  iram0_2_seg (RX) :                 org = 0x400D0018, len = 0x330000-0x18

  /*
    (0x18 offset above is a convenience for the app binary image generation. Flash cache has 64KB pages. The .bin file
    which is flashed to the chip has a 0x18 byte file header. Setting this offset makes it simple to meet the flash
    cache MMU's constraint that (paddr % 64KB == vaddr % 64KB).)
  */


  /* Shared data RAM, excluding memory reserved for ROM bss/data/stack.

     Enabling Bluetooth & Trace Memory features in menuconfig will decrease
     the amount of RAM available.

     Note: Length of this section *should* be 0x50000, and this extra DRAM is available
     in heap at runtime. However due to static ROM memory usage at this 176KB mark, the
     additional static memory temporarily cannot be used.
  */
  dram0_0_seg (RW) :                 org = 0x3FFB0000 + CONFIG_BT_RESERVE_DRAM,
                                     len = 0x2c200 - CONFIG_BT_RESERVE_DRAM

  /* Flash mapped constant data */
  drom0_0_seg (R) :                  org = 0x3F400018, len = 0x400000-0x18

  /* (See iram0_2_seg for meaning of 0x18 offset in the above.) */

  /* RTC fast memory (executable). Persists over deep sleep.
   */
  rtc_iram_seg(RWX) :                org = 0x400C0000, len = 0x2000
  
  /* RTC fast memory (same block as above), viewed from data bus */
  rtc_data_seg(RW) :                 org = 0x3ff80000, len = 0x2000

  /* RTC slow memory (data accessible). Persists over deep sleep.

     Start of RTC slow memory is reserved for ULP co-processor code + data, if enabled.
  */
  rtc_slow_seg(RW)  :                org = 0x50000000 + CONFIG_ULP_COPROC_RESERVE_MEM,
                                     len = 0x1000 - CONFIG_ULP_COPROC_RESERVE_MEM

  /* external memory ,including data and text */
  extern_ram_seg(RWX)  :             org = 0x3F800000,
                                     len = 0x400000
}
```

**Comment by xuhongv** [comment]
- 这个你们没落实到 esp32 吧。之前存在的 wifi 任务栈分配大小都折腾我好久，没办法，只能改为 esp8266 了；现在要把这个 esp32接入 joylink 作为技术储备。

**Comment by xiewenxiang** [comment]
> 我现在的 esp32分区表足够多的：
> 
> ```
> nvs,      data, nvs,     0x9000,  0x4000
> otadata,  data, ota,     0xd000,  0x2000
> phy_init, data, phy,     0xf000,  0x1000
> factory,  0,    0,       0x10000,   1200K
> ota_0,    0,    ota_0,   ,          1200K
> ota_1,    0,    ota_1,   ,          1200K
> ```

这个1200K 够吗？你看下你编译出来的bin呢

**Comment by xiewenxiang** [comment]
> * 这个你们没落实到 esp32 吧。之前存在的 wifi 任务栈分配大小都折腾我好久，没办法，只能改为 esp8266 了；现在要把这个 esp32接入 joylink 作为技术储备。

joylink 已经不支持 smartconfig，目前在 softap和thunder配网上不会再出现 wifi task堆栈溢出的问题

**Comment by xuhongv** [comment]
现在没法编译出来固件 @xiewenxiang  麻烦你提供下你的esp32 的编译环境，谢谢

**Comment by xiewenxiang** [comment]
esp-joylink commit e50f9c53e6ec93eab0e4f8bd11a477719609bc7f

esp-idf commit 6ccb4cf5b7d1fdddb8c2492f9cbc926abaf230df

Toolchain path: /Users/xiewenxiang/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0

**Comment by xuhongv** [comment]
这个是哪个分支的 idf 。

**Comment by xiewenxiang** [comment]
3.3

![image](https://user-images.githubusercontent.com/26754847/69225383-3d171680-0bb9-11ea-9dc2-dcaa9e51075c.png)

**Comment by hizhsj** [comment]
> [joylink_8266_partitions.csv.zip](https://github.com/espressif/esp-joylink/files/3868158/joylink_8266_partitions.csv.zip)
> 
> @hizhsj 用这个 partition table

请问这个要怎么使用？

**Comment by xiewenxiang** [comment]
@hizhsj  解压缩之后是一个 .csv 文件，你把它放在 light_demo 目录下，然后make menuconfig -> partition table -> custom partition table csv

然后第二行把 这个文件的名字输入

**Comment by hizhsj** [comment]
> @hizhsj 解压缩之后是一个 .csv 文件，你把它放在 light_demo 目录下，然后make menuconfig -> partition table -> custom partition table csv
> 
> 然后第二行把 这个文件的名字输入

按照这个操作之后，设备启动不了，一直报错。
I (50) boot: compile time 17:55:37
I (52) qio_mode: Enabling default flash chip QIO
I (56) boot: SPI Speed      : 40MHz
I (60) boot: SPI Mode       : QIO
I (64) boot: SPI Flash Size : 2MB
I (68) boot: Partition Table:
I (72) boot: ## Label            Usage          Type ST Offset   Length
I (79) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (86) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (94) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (101) boot:  3 ota_0            OTA app          00 10 00010000 000e0000
I (109) boot:  4 customize        unknown          40 00 00100000 00002000
I (116) boot:  5 ota_1            OTA app          00 11 00110000 000e0000
I (124) boot: End of partition table
I (128) boot: No factory image, trying OTA 0
I (133) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x8b900 (571648) map
I (334) esp_image: segment 1: paddr=0x0009b918 vaddr=0x4029b910 size=0x198d0 (104656) map
I (370) esp_image: segment 2: paddr=0x000b51f0 vaddr=0x3ffe8000 size=0x02f98 ( 12184) load
I (375) esp_image: segment 3: paddr=0x000b8190 vaddr=0x40100000 size=0x00b80 (  2944) load
I (378) esp_image: segment 4: paddr=0x000b8d18 vaddr=0x40100b80 size=0x05e88 ( 24200) load
I (394) boot: Loaded app from partition at offset 0x10000
assertion "nvs_flash_init() == 0" failed: file "startup.c", line 84, function: user_init_entry
E (413) ABORT: Error found and abort!
Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled.

**Comment by xiewenxiang** [comment]
改了partiton，烧录之前，把板子完整的擦除一遍

**Comment by xuhongv** [comment]
我上面的 1.2m不够大，现在都 1.6m ，有啥办法可以减少吗

```
E (764) esp_image: Image length 1610896 doesn't fit in partition length 1228800
E (764) boot: Factory app partition is not bootable
E (766) esp_image: image at 0x140000 has invalid magic byte
E (772) boot_comm: mismatch chip ID, expected 0, found 8
E (778) boot_comm: can't run on lower chip revision, expected 1, found 82
W (786) esp_image: image at 0x140000 has invalid SPI mode 52
E (792) boot: OTA app partition slot 0 is not bootable
E (798) esp_image: image at 0x270000 has invalid magic byte
E (804) boot_comm: mismatch chip ID, expected 0, found 65535
E (810) boot_comm: can't run on lower chip revision, expected 1, found 255

```

**Comment by xiewenxiang** [comment]
@xuhongv 关闭log会少一点，但是不会少太多

你现在是 刚超过1.5M 还是逼近1.6M？

**Comment by xuhongv** [comment]
![image](https://user-images.githubusercontent.com/25237870/69230969-41483180-0bc3-11ea-9604-3cb39c2cd409.png)

我先修改下分区吧 ，不要 factory

**Comment by xiewenxiang** [comment]
OK

**Comment by xiewenxiang** [comment]
@hizhsj 现在可以了吗？

**Comment by xiewenxiang** [comment]
@hizhsj 如果还有问题，请重新打开这个issues
