### ISSUE TITLE
一机一密的烧录方式

### ISSUE THREAD

**Issue by hizhsj** [espressif/esp-joylink#19]
现在京东平台使用的一机一密的验证方式，要先将MAC上传京东平台，京东会生成对应的私钥，然后用户再把私钥下载下来，烧录的时候，除了程序，还要把MAC和对应的私钥一并烧录，否则就无法通过京东验证，从而无法配网和使用。请问，乐鑫这边有什么好的解决方案吗？可以在烧录程序的时候，一并把MAC和私钥烧录进去，要能适用批量化生产。

**Comment by xiewenxiang** [comment]
举个例子，把MAC和KEY弄在一起
MAC的长度的是12字节，KEY的长度是固定的，64字节，一前一后拼起来，是固定长度76字节
然后把这个字符串转成HEX格式，烧录在  0x100000地址，然后改下这两个函数：


烧录固件的时候要分两次烧录，一次是通用的固件，另一次烧录这些MAC和KEY，每个都不同，你们可以做一个工具，批量生成这些MAC+KEY的BIN

**Comment by hizhsj** [comment]
用户保存的其他信息，比如feedid，应该是存储在0x10000开始的这段FLASH里面的，会不会有影响？有生成bin的工具示例吗，参考一下。

**Comment by xiewenxiang** [comment]
@hizhsj 

上面的示例是写在 0x100000，不是0x10000, 其实就是分配一个小小的partition分区表来存储就OK了

**Comment by hizhsj** [comment]
看错了，0x10000是OTA的区域，0x100000才是用户存储的区域。

**Comment by xiewenxiang** [comment]
如果这里还有问题，可以重新打开这个 issue
