### ISSUE TITLE
如何正确调用函数删除设备，使其重新配网 (AEGHB-55)

### ISSUE THREAD

**Issue by xmywushu** [espressif/esp-joylink#26]
目前想实现配网指令操作，使已配网的设备能重新配网，调用方法如下：
     esp_joylink_wifi_clear_info();
     joylink_sub_dev_del_by_mac();
其中joylink_sub_dev_del_by_mac实现如下：
    char mac_buf[12] = {0x0};
    joylink_dev_get_user_mac(mac_buf);
    JLSubDevData_t *info_out = NULL;
    joylink_sub_dev_get_by_deviceid(mac_buf,info_out);
    //printf("delete feedid: %s\n", info_out->feedid);
    //joylink_sub_dev_del(info_out->feedid);
    joylink_dev_sub_unbind(info_out->feedid);
是根据mac调用删除，但是APP删除后，再次配网会失败，请问应该如何去做呢？

**Comment by xcguang** [comment]
提示的什么错误？可以贴出来看一下

**Comment by xmywushu** [comment]
这是相关日志：
[2023-02-01 11:24:22.360]# RECV ASCII>
[0m[1;36m[INFO][2023-02-01 03:24:23.090][joylink_softap_protocal.c][joylink_softap_data_packet_handle][623]

Receive the ssid and pass success


[0m[1;36m[INFO][2023-02-01 03:24:23.092][joylink_softap_start.c][joylink_softap_start][356]

softap finsh,ssid->TP-LINK_E9A1,pass->fl123456

[0m[1;36m[INFO][2023-02-01 03:24:23.105][joylink_softap_start.c][release_resource][402]

close fd udp_fd

[0m[1;36m[INFO][2023-02-01 03:24:23.114][joylink_softap_start.c][release_resource][409]

close fd tcp_fd
[2023-02-01 11:24:22.414]# RECV ASCII>


[0m[1;32m[DEBUG][2023-02-01 03:24:23.124][joylink_softap.c][jl_softap_connect_wifi_router][101]

--  ready to connect to AP

[0mI (23020) wifi:mode : sta (68:ab:bc:b0:41:9c)

[2023-02-01 11:24:23.039]# RECV ASCII>
I (23640) wifi:new:<6,2>, old:<9,0>, ap:<255,255>, sta:<6,2>, prof:9

[2023-02-01 11:24:23.666]# RECV ASCII>
I (24230) wifi:state: init -> auth (b0)
I (24240) wifi:state: auth -> assoc (0)
I (24270) wifi:state: assoc -> run (10)

[2023-02-01 11:24:26.784]# RECV ASCII>
I (27370) wifi:state: run -> init (fc0)
I (27370) wifi:new:<6,0>, old:<6,2>, ap:<255,255>, sta:<6,2>, prof:9
I (27370) wifi:new:<6,0>, old:<6,0>, ap:<255,255>, sta:<6,2>, prof:9
这里就不动了
正常配网后面是这样的：

[2023-02-01 10:45:11.270]# RECV ASCII>
I (33840) wifi:new:<6,2>, old:<9,0>, ap:<255,255>, sta:<6,2>, prof:9

[2023-02-01 10:45:11.876]# RECV ASCII>
I (34430) wifi:state: init -> auth (b0)
I (34440) wifi:state: auth -> assoc (0)
I (34450) wifi:state: assoc -> run (10)

///////////////////////////////////////////////////////////////////////////////////////////
[2023-02-01 10:45:12.017]# RECV ASCII>
I (34560) wifi:connected with TP-LINK_E9A1, aid = 6, channel 6, 40D, bssid = d0:76:e7:53:e9:a1
I (34570) wifi:security: WPA2-PSK, phy: bgn, rssi: -26
I (34570) wifi:pm start, type: 1

I (34570) wifi:set rx beacon pti, rx_bcn_pti: 14, bcn_timeout: 14, mt_pti: 25000, mt_time: 10000

[2023-02-01 10:45:12.094]# RECV ASCII>
I (34660) wifi:BcnInt:102400, DTIM:1
后面省略
////////////////////////////////////////////////////////////////////////////////////////////

不过多次触发配网，偶尔又可以成功！

**Comment by xcguang** [comment]
看着 log 你这已经去连接了
1. 重新配网，清除配置后可以重启一下 esp_restart() 试试
2. 重新配置的时候，配置一个新的路由器是否可以？

**Comment by xmywushu** [comment]
都试了，不太行
一个规律就是：
第一次触发配网，执行函数后，再去配网失败，重新触发，再去配网，第二次一般就可以

**Comment by xcguang** [comment]
在清除 Wi-Fi 配置前，有进行 Wi-Fi 断开的动作吗？先断开一下试试。看着你的描述应该整体流程问题不大，并且 log 也去连接了

**Comment by xmywushu** [comment]
您好，这样确实可以解决！目前看稳定性还可以！多谢指导！
