### ISSUE TITLE
no blank_12k.bin creat!

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-joylink#3]
- I succeed build thr project ,but no this blank_12k.bin to creat?

**Comment by Eavo** [comment]
Hi, sorry for late reply. Could you please describe the bin for details? I cannot find which bin you mentioned. Thanks.

**Comment by xuhongv** [comment]
i can fine the blank_12k in other project

**Comment by Eavo** [comment]
We updated Joylink SDK 2 months ago, could you please try the latest SDK based on Joylink v2.0.8?

**Comment by Eavo** [comment]
If any issue, please feel free to reopen it. Thanks.
