### ISSUE TITLE
Does it support lan control

### ISSUE THREAD

**Issue by zhijianli88** [espressif/esp-joylink#4]
i saw this sample disabled lan control, so want to know whether it supports lan control or not

**Comment by Eavo** [comment]
Sorry for late reply. It supports lan control, please refer to _LightManage_t _g_lightMgr_ in _sp-joylink/port/extern/joylink_extern.c_
![ggg4 rhel5u b152 5beg](https://user-images.githubusercontent.com/31977734/50428933-278c6480-08f6-11e9-97e0-6f0207a069ed.jpg)

**Comment by Eavo** [comment]
If any issue, pelease feel free to reopen it. Thanks.
