### ISSUE TITLE
esp8266平台的 OTA 功能失败，APP一直显示在下载固件中？

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-joylink#7]
- 最近做到了 OTA功能，发现当app点击升级固件后，app显示如下：

- 但是在 esp8266 的串口上提示还是在与京东云在 心跳回复？

![image](https://user-images.githubusercontent.com/25237870/54116014-cf5efc00-4428-11e9-8901-0872ca20e32e.png)

**Comment by xiewenxiang** [comment]
心跳的确会持续的，你可以看下有没有在持续收包

**Comment by xuhongv** [comment]
- 没有持续收到包。。请问下，当前本地固件版本定义是在哪里的？

**Comment by xiewenxiang** [comment]
版本定义的地方都是无效的，你在京东后台上传的版本随便你怎么定义，后台只会推送最后一次上传的

**Comment by xiewenxiang** [comment]
OTA 的代码在 joy link_upgrade.c里面，你可以先看下问题出在哪里

比如是否因为没有内存导致 OTA的 task creat失败

**Comment by xiewenxiang** [comment]
抱歉，不好意思，忘了跟你说了，master分支上OTA已经加上了，但是上次给你的PATCH没有把这个加上

OTA升级的版本控制，我目前了解的也就是这样，版本的定义好像无效

**Comment by xuhongv** [comment]
- **版本号可自定义，云端将定义的版本号作为消息内容发给小京鱼APP。而云端记录版本高低的方式是：将第一次上传的版本号认为1，每次上传固件，后台版本号自动加1。SDK上报版本号同样为整数，云端对比版本号后，决定是否推送升级消息。**

- 目前的 ota我已经全部完成了！见官网文档说明，这个设备本地还是要这个版本上报的，需要在这个文件` joylink_extern.c` 以及 joylink_dev_sdk_2.0.09\joylink 下面的 `joylink_dev_sdk.c `要修改版本号，这里在基础上增加了个全局编译，就是在 `make menuconfig` 设置！

-  `joylink_extern.c `
![image](https://user-images.githubusercontent.com/25237870/54180581-efe58f80-44d6-11e9-83b3-d4f692c01da1.png)

-  `joylink_dev_sdk.c `
![image](https://user-images.githubusercontent.com/25237870/54180750-55398080-44d7-11e9-9b0e-de1100e6a28a.png)

**Comment by shun-dgut** [comment]
我加入ota，但是会收到Task watchdog got triggered.然后ota失败了

E_JLRetCode_t
joylink_dev_ota(JLOtaOrder_t *otaOrder)
{
if(NULL == otaOrder){
return -1;
}
int ret = E_RET_OK;

log_debug("serial:%d | feedid:%s | productuuid:%s | version:%d | versionname:%s | crc32:%d | url:%s\n",
otaOrder->serial, otaOrder->feedid, otaOrder->productuuid, otaOrder->version, 
otaOrder->versionname, otaOrder->crc32, otaOrder->url);

// ret = esp_ota_task_start((const char*)otaOrder->url);
// printf("========ota===========\r\n");
//xTaskCreate(joylink_ota_task, "joylink_ota_task", 1024*8, (void * const)otaOrder, 2, NULL);
joylink_ota_task(otaOrder);
return ret;
}
确实在ota，但是日志会收到

Task watchdog got triggered.
Task stack [joylink_main_ta] stack from [0x3fffd58c] to [0x3ffff588], total [8192] size
