### ISSUE TITLE
no partition file found

### ISSUE THREAD

**Issue by hizhsj** [espressif/esp-joylink#8]

**Comment by Eavo** [comment]
Could you please help provide more details for this issue?

**Comment by hizhsj** [comment]
`#include "esp_log.h"
#include "lwip/err.h"
#include "lwip/sockets.h"
#include "lwip/sys.h"
#include "lwip/netdb.h"
#include "lwip/dns.h"
#include "freertos/timers.h"
#include "esp_ota_ops.h"
#include "esp_partition.h"

#include "tcpip_adapter.h"

in joylink_upgrade.c file, some headfile cannot be found, like "esp_ota_ops.h" "tcpip_adapter.h"

**Comment by xiewenxiang** [comment]
Maybe the  ESP-IDF didn't update the submodule.
