### ISSUE TITLE
ESP8266编译出错

### ISSUE THREAD

**Issue by jsonsiyuan** [espressif/esp-joylink#9]
n file included from /mnt/hgfs/linux_share/esp-joylink/port/include/netinet/in.h:5:0,
                 from /mnt/hgfs/linux_share/esp-joylink/joylink_cloud/joylink_dev_sdk_2.0.09/json/../joylink/joylink_sub_dev.h:6,
                 from /mnt/hgfs/linux_share/esp-joylink/joylink_cloud/joylink_dev_sdk_2.0.09/json/joylink_json.h:10,
                 from /mnt/hgfs/linux_share/esp-joylink/joylink_cloud/joylink_dev_sdk_2.0.09/agent/joylink_agent_json.c:15:
/home/sun/esp/ESP8266_RTOS_SDK/components/lwip/lwip/src/include/lwip/sockets.h:585:51: error: conflicting types for 'lwip_ioctl'
 #define ioctl(s,cmd,argp)                         lwip_ioctl(s,cmd,argp)
                                                   ^
/home/sun/esp/ESP8266_RTOS_SDK/components/vfs/include/sys/ioctl.h:21:5: note: in expansion of macro 'ioctl'
 int ioctl(int fd, int request, ...);

**Comment by xiewenxiang** [comment]
8266SDK用3.1分支，commit: db1b044312
